### ISSUE TITLE
UbioWeldContinuum does not find dependency

### ISSUE THREAD

**Issue by Braste** [net-lisias-ksp/UbioWeldContinuum#2]
When loading the vehicle assembly, i get the following error:

`[WeldingTool] ERROR: UdioWeldingLtd.UbioZurWeldingLtd raised Exception System.IO.FileNotFoundException: Could not load a file or assembly 'KSPe.UI, Version=2.1.1.6, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'KSPe.UI, Version=2.1.1.6, Culture=neutral, PublicKeyToken=null'
at UbioWeldingLtd.UbioZurWeldingLtd.OnGUI()
[0x00000] in <26f19f055aeb435b814062ac98c92c5b>:0 at ex:0`

Prior to that when i open the console in main menu i get: 

`Excpetion: FileNotFoundException: Could not load file or assembly 'KSPe.UI, Version=2.1.0.16, Culture=neutral, PublicKeyToken=null' or one of its dependencies`

I use KSP version 1.10.0.2917 and the latest release of the following mods on a new game:
https://github.com/net-lisias-ksp/UbioWeldContinuum
https://github.com/net-lisias-ksp/TweakScale
https://github.com/net-lisias-ksp/ModuleManager
https://github.com/net-lisias-ksp/KSPAPIExtensions
https://github.com/net-lisias-ksp/KSP-Recall
https://github.com/net-lisias-ksp/ModuleManagerWatchDog
https://github.com/net-lisias-kspu/ToolbarControl

**Comment by Lisias** [comment]
Hi.

You need to install KSP API Extensions and Click Through Blocker too.

https://github.com/net-lisias-ksp/KSPAPIExtensions
https://github.com/linuxgurugamer/ClickThroughBlocker

Please remember that this tool really understands only parts from the 1.4.5 era - this thing just doesn't understands VARIANTs yet (I **think** I can do something about it while I'm doing the same on TweakScale, that also doesn't really understand variants yet).

I usually recommend doing the welding using KSP 1.4.5, and then copy the __LOCAL folder into your 1.10 for use - but with some parts on the zDeprecated folder (as new versions of the part were released by Squad), this stunt may not work as it used to do.

Ping me here if you need more assistance on the matter.

**Comment by 7ranceaddic7** [comment]
SUGGESTION:  Discard variants.

Tell everyone: what you weld, is what you get.

Full Stop.

As long as it welds the parts correctly, that should be sufficient for now.
You can tackle permitting variants on welded parts later.

(Preferably, after **YOU TAKE A VACATION** with many, MANY beers. :))

**Comment by Braste** [comment]
> Hi.
> 
> You need to install KSP API Extensions and Click Through Blocker too.
> 
> https://github.com/net-lisias-ksp/KSPAPIExtensions
> https://github.com/linuxgurugamer/ClickThroughBlocker
> 
> Please remember that this tool really understands only parts from the 1.4.5 era - this thing just doesn't understands VARIANTs yet (I **think** I can do something about it while I'm doing the same on TweakScale, that also doesn't really understand variants yet).
> 
> I usually recommend doing the welding using KSP 1.4.5, and then copy the __LOCAL folder into your 1.10 for use - but with some parts on the zDeprecated folder (as new versions of the part were released by Squad), this stunt may not work as it used to do.
> 
> Ping me here if you need more assistance on the matter.

I already use https://github.com/net-lisias-ksp/KSPAPIExtensions :)

I installed Click Through Blocker now and copied the KDPe.UI.dll into every of the mod folders for testing, C# can be a bi.., now I get another error, when i load the vehicle building:
`Exception: NullReferenceException: Object reference not set to an instance of an object`
`Error: [WeldingTool] ERROR: UbioWeldingLtd.UbioZurWeldingLtd raised Excpetion System.NullReferenceException: Object reference not set to an instance of an object at UbioWeldingLtd.UbioWeldingLtd.Update() [0x00006] in <26f19f055aeb435b814062ac98c92c5b>:0 at ex:0`
I checked the code and there is not much going on in the Update method, so i strongly believe it has something to do with an incompatibility with ToolbarControl.

**Comment by Lisias** [comment]
Humm.. The borked toolbar is side-effect. The main reason is the Awake handler borking:

```
[ERR 07:57:44.851] [WeldingTool] ERROR: UbioWeldingLtd.UbioZurWeldingLtd raised Exception System.NullReferenceException: Object reference not set to an instance o
f an object
  at UbioWeldingLtd.DatabaseHandler.initMMAssembly () [0x00055] in <26f19f055aeb435b814062ac98c92c5b>:0
  at UbioWeldingLtd.UbioZurWeldingLtd.HandleAwake () [0x00185] in <26f19f055aeb435b814062ac98c92c5b>:0
  at UbioWeldingLtd.UbioZurWeldingLtd.Awake () [0x00000] in <26f19f055aeb435b814062ac98c92c5b>:0  at ex:0

[EXC 07:57:44.856] NullReferenceException: Object reference not set to an instance of an object
        UbioWeldingLtd.DatabaseHandler.initMMAssembly () (at <26f19f055aeb435b814062ac98c92c5b>:0)
        UbioWeldingLtd.UbioZurWeldingLtd.HandleAwake () (at <26f19f055aeb435b814062ac98c92c5b>:0)
        UbioWeldingLtd.UbioZurWeldingLtd.Awake () (at <26f19f055aeb435b814062ac98c92c5b>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        KSPe.Util.Log.UnityLogDecorator:UnityEngine.ILogHandler.LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:LogException(Exception)
        KSPe.Util.Log.UnityLogger:logException(String, Exception)
        KSPe.Util.Log.Logger:error(Object, Exception)
        UbioWeldingLtd.Log:ex(MonoBehaviour, Exception)
        UbioWeldingLtd.UbioZurWeldingLtd:Awake()
        UnityEngine.GameObject:AddComponent(Type)
        AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
        AddonLoader:StartAddons(Startup)
        AddonLoader:OnLevelLoaded(GameScenes)
        AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
        UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)
```

I need to assess the situation. I'm working on it.

**Comment by Lisias** [comment]
The problem was smelling under my nose and yet I missed it. It's something on the Reflection system again.

`UbioWeldingLtd.DatabaseHandler.initMMAssembly ` is borking, and since it is called on the Awake, Awake borks before initialising the Toolbar - and so the Update borks on trying to update it.

Oh, well... Now I have to understand what's broken on the Reflection in order to overcome it. This has already [bitten my ass before](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-141-tweakscale-under-lisias-management-24317-2020-0710/&do=findComment&comment=3798088), by the way....

Well... I'm working on it, but this can take a bit...

**Comment by Lisias** [comment]
Holly Molly... It's not the Reflection system... I had bitten my own ass without knowing it!

@Braste , as a workaround delete `GameData/666_ModuleManagerWatchDog.dll`. The code on `initMMAssembly` that looks for Module Manager is too much optimistic, and it's borking because it flags anything that starts with "ModuleManager" as being the MM itself!!

I will issue a new release for the Welding tool with this fixed after fixing the code and testing it propperly. I need to confirm on previous Module Manager versions how was the naming convention to keep backwards compatibility.

![Screen Shot 2020-07-11 at 09 20 54](https://user-images.githubusercontent.com/64334/87224016-12e8b380-c358-11ea-8554-81a43c77bbd0.png)

**Comment by 7ranceaddic7** [comment]
XD.

Dude, you need a break.

**Comment by Lisias** [comment]
> Dude, you need a break.

Eventually. But today I have a important migration on our biggest customer at night, and I need to be awake on the whole process, and these little puzzles are motivating enough to do the trick.

-- -- -- 

In time, I dug into Module Manager's source code until commit 4aba55939c965ad8fda3e37d90196da4857898f5 from Brent era (2013!), and in **every single release**, the name of the thing was exactly `ModuleManager`, not "`ModuleManager`*something*" .

There isn't and never was a reason to compare the Assembly names using `.StartsWith` as it's being done now.

Well, fixed. New release in a few minutes.

**Comment by Lisias** [comment]
Fixed on commit https://github.com/net-lisias-ksp/UbioWeldContinuum/commit/20901df7446b41e09dda48568f4219e97780695a

**Comment by 7ranceaddic7** [comment]
Yeah, I just did a search "assembly.GetName().Name.StartsWith" "ModuleManager".

OOpsie.
